### ISSUE TITLE
Considering a support TTreeFiend?

### ISSUE THREAD

**Issue by rmadar** [rmadar/tree-gonalyzer#15]
This would depend mostly on whether it is possible/easy to add in go-hep/hep (@sbinet?). I know it might not be an everyday use case but it is a quite nice feature to play around.

**Comment by sbinet** [comment]
what kind of the many things `TTreeFriend` can do would you like to see in `go-hep.org/x/hep/groot`?

**Comment by rmadar** [comment]
I was thinking about the main feature of the `TTreeFriend`, *i.e.*, "pairing" several trees with the main one, and then access the variables of all trees in a user-transparent way. Something like:
```go
// Get several trees 
tMain := fileMain.Get("treeMain")(.rtree.Tree)
fFriend1 := file1.Get("tree1")(.rtree.Tree)
fFriend2 := file2.Get("tree2")(.rtree.Tree)

// Pairing them
tMain.AddFriend(tFriend1)
tMain.AddFriend(tFriend2)

// Create a Reader accessing info from 'tree1' and 'tree2' directly from 'tMain'.
// In case tree names are different, one could use them as prefix 
// in the branch names.
r := rtree.NewReader(tMain, []rtree.ReadVar{
        {Name: "one", Value: &v1},
        {Name: "tree1.two", Value: &v2},
        {Name: "tree2.three", Value: &v3},
    } 
```

**Comment by sbinet** [comment]
ok, so the "join" of a database. _i.e.:_ kind of a "horizontal-cat" (adding columns), not to be confused with a "vertical-cat" (like the TChains).

I suppose you'd also want this to work with `rtree.Reader.FormulaFunc` ? :)

could you file an issue against `go-hep/hep`?

**Comment by rmadar** [comment]
Exactly! I filled https://github.com/go-hep/hep/issues/723. And yes, it would be very nice to have it work with `FormulaFunc` :) !

**Comment by sbinet** [comment]
fixed w/ https://github.com/go-hep/hep/pull/726.

**Comment by rmadar** [comment]
Perfect, thanks! For some reason, I need to resolve https://github.com/rmadar/tree-gonalyzer/issues/14 before I'll implement `rtree.Join()`

**Comment by sbinet** [comment]
on second thoughts, maybe it isn't such a good idea:
- it's a bit magical
- it might prevent the Go linker from removing the unused formula implementations and thus bloat a bit the resulting binary (_ie:_ increase of the final executable)

**Comment by rmadar** [comment]
You mean the join feature?

**Comment by sbinet** [comment]
no, the automagical registration of the `rfunc` concrete types.
(yes, I probably replied on the wrong thread...)

**Comment by rmadar** [comment]
It works nicely! This is a plot which takes some hit times in one tree, the calibration constant in another  and calibrate each time with it's proper constant (using `rfunc.Formula`):

![image](https://user-images.githubusercontent.com/30081646/83646723-552e1080-a5b4-11ea-9281-a8fea738d4c3.png)

closing!
